### ISSUE TITLE
2.0.4-v.1 - pedigree boxes have different dimensions

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#1]
In the pedigree chart of your [demo family tree](https://genea.jaubart.com/wt) I see that all boxes have the same dimensions.

But in my own family tree this boxes have different dimensions, which looks restless and messy:
![msedge_webtrees2 0 4-pedigree-right](https://user-images.githubusercontent.com/46184729/83601222-72d98680-a570-11ea-8ff8-bc75b804aa48.png)

Is it possible to give all pedigree boxes the same dimensions?

_Tested configuration_
Device: desktop pc
OS: Windows10 x64 Home v1909
Browsers: Edge v83.0.478.37 and Firefox v77.0
webtrees: 2.0.4

**Comment by jon48** [comment]
My website is still using the v1.7 of the theme, as I need to update other custom modules before being able to upgrade to v2.0, so it is not a good reference yet.

I have a good idea of where the issue is, as I was trying to use the full width, not setting a constant chart box width , but in your use case, it indeed does not work well, There is a simple fix, but I would like to investigate if I can still take advantage of the full width before committing.
Hopefully that should as well fix the vertical misalignment I can see on the left part.

**Comment by TheDutchJewel** [comment]
For your info: the Hour Glass and other charts looks fine, just not the pedigree one.

**Comment by jon48** [comment]
I have implemented at least the simple fix, setting a constant width.
Can you try replacing the file `/modules_v4/myartjaub_ruraltheme/resources/css/rural.min.css` with the file  in [this archive](https://github.com/jon48/webtrees-theme-rural/files/4725957/rural.min.css.zip)?

**Comment by TheDutchJewel** [comment]
The simple fix works fine. Thank You!
