### ISSUE TITLE
2.0.4-v.2 - Windows key + Left arrow - scaling problem

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#10]
When I adjust the size of the browser page with the `Windows key + the left arrow`, the right side of boxes with the family members, does not look good:

![afbeelding](https://user-images.githubusercontent.com/46184729/84568245-4e568900-ad7e-11ea-8fd3-7c76df649ec1.png)

![afbeelding](https://user-images.githubusercontent.com/46184729/84568248-531b3d00-ad7e-11ea-9207-d623c619e0ae.png)

_Tested configuration_
Device: desktop pc
OS: Windows10 x64 Home v1909
Browsers: Edge v83.0.478.45 and Firefox v77.0.1
webtrees: 2.0.5
PHP: 7.3.18

**Comment by TheDutchJewel** [comment]
The problem seems to be caused by the [Vesta Webtrees Custom Module 'Classic Look & Feel'](https://cissee.de/).
If I disable this module, everything looks fine:
![afbeelding](https://user-images.githubusercontent.com/46184729/84620660-dcdf1d80-aed8-11ea-8a2b-582fa6e595c7.png)

I opened an [issue on github/vesta-webtrees-2-custom-modules/vesta_classic_laf](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues/11), hoping the author will look into it.

**Comment by jon48** [comment]
Hello,
This is not entirely due to the Vesta module, I can reproduce it when I reduce enough with some long names.
![image](https://user-images.githubusercontent.com/5150782/84942398-abce3b00-b0da-11ea-9f77-11f1d4ab9011.png)

As mentioned by @ric2016 in https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues/11#issuecomment-643970204, the sidebar is a bit problematic, and I am not even sure there will be a good approach to it (the standard webtrees theme actually has the issue as well).

I can think of 2 attempts to fix it, but I am not really convinced by the outcome of any of them, which have impact even when there is enough space:
- allow to break in the middle of names `word-break: break-all;`
![image](https://user-images.githubusercontent.com/5150782/84942787-49c20580-b0db-11ea-8ac4-814eebc0437b.png)
- or hiding the overflow, and have a scrollbar `overflow-y: auto;`
![image](https://user-images.githubusercontent.com/5150782/84942849-678f6a80-b0db-11ea-9601-f05e7f6ef424.png)

I am happy to get your opinion on any of those options, but I think this is one I will leave as is, and accept the overflow.

**Comment by ric2016** [comment]
I tried various options as well, I think a fixed table layout works best:

```
[dir] .wt-family-navigator-family {
  table-layout: fixed;
}

[dir] .wt-family-navigator-family th {
  width: 30%;
}

[dir] .wt-family-navigator-family .dropdown-toggle {
  white-space: normal;
}

[dir] .wt-family-navigator-family .dropdown-item {
  white-space: normal;
}
```

is what I ended up with. This breaks long names properly (only the family dropdown still is problematic), and the columbs align nicely across multiple tables.

**Comment by TheDutchJewel** [comment]
>I am happy to get your opinion on any of those options, but I think this is one I will leave as is, and accept the overflow.

Both have their own issues and none of them looks better than the overflow problem.
If it can't be solved completely, I understand if you'll leave it as it is.

**Comment by jon48** [comment]
Thanks @ric2016 , your suggestion looks like a good compromise indeed. I will go for it.

![image](https://user-images.githubusercontent.com/5150782/85172205-7ce5cf80-b268-11ea-8e2d-946aab218980.png)
