### ISSUE TITLE
Notify users when a new release is available

### ISSUE THREAD

**Issue by JustCarmen** [jon48/webtrees-theme-rural#32]
Could you please add the notification link to check for new releases in your modules.php file?

You should add the function 'customModuleLatestVersionUrl'.

I mainly use your theme to test it against my own custom modules but I really miss this feature, so I can imagine that it would be handy for other users too.

**Comment by jon48** [comment]
This is on the to-do list, but still have not been able to decide on the URL itself, as I would like to expose a endpoint a bit more advanced than just a static text file (so that a newer version is not suggested if not compatible with the installed webtrees version).

I will add something (even if static) for the next release.

**Comment by jon48** [comment]
Feature added in 155fc9702c463fe3e11a742bd0366b062caed01d
