### ISSUE TITLE
Button overflow?

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#61]
![Screenshot_20230321-152215_Chrome](https://user-images.githubusercontent.com/6124739/226636501-342eda45-3831-4ff6-9dbb-39e4b49fa2a3.jpg)

**Comment by jon48** [comment]
This problem is a difficult one to address, as the alternative is not necessarily visually nice either.
Here is an example of allowing breaking words to fit the frame, some of the buttons becomes very difficult to read, and some words are cut at places where it does not make much sense.

![image](https://user-images.githubusercontent.com/5150782/229346391-61ff2e6f-5188-4b8d-9dce-aabb90b8eb69.png)

Furthermore, the CSS directives allowing that are not very flexible, and leave the browser "deciding" many factors, so that can lead to worse visual displays even in larger resolutions.
This is one instance where I think that the defect is better than the "fixed" alternative, so I do not plan to fix it.

For information, the core themes also shows this behavior (arguably they are marginally more forgiving, as they have slightly more width available):

![image](https://user-images.githubusercontent.com/5150782/229346726-af4314f2-e7f1-462e-86b5-1496deb9c2b7.png)

**Comment by arbor95** [comment]
ok, thx
