### ISSUE TITLE
compatibility to "Fancy imagebar"

### ISSUE THREAD

**Issue by arbor95** [jon48/webtrees-theme-rural#67]
The compatibility to "Fancy imagebar" is lost with last change. Can you please correct, so that the imagebar is again within the borders area of rural?

**Comment by ChrisSka** [comment]
I cannot confirm this. It is displayed exactly right for me.

![image](https://github.com/user-attachments/assets/6aec636c-9546-4877-abb8-df8cdff32564)

**Comment by arbor95** [comment]
ok, reason is I did rename the dir myartjaub_ruraltheme, sorry.
Is there a way for renaming?

**Comment by ChrisSka** [comment]
Simply connect via FTP and rename the folder again. Or what exactly is the problem?

**Comment by arbor95** [comment]
the theme should not depend on the name of the installed directory.

**Comment by jon48** [comment]
The theme itself does not depend on the name of the installed directory.
The problem is with the Fancy Image Bar module which refers explicitly `.wt-theme-_myartjaub_ruraltheme_` to identify the theme, but that class name is dependent on the folder (the logic is in the core code of webtrees).

In Carmen's defence, this is not an easy one to get right, as there is not much currently in the inter-module communication that would allow knowing the module is there, and make the class name dynamic.
I would recommend sticking with the standard folder names when mixing modules from different authors.

**Comment by arbor95** [comment]
thx for the explanation.
