### ISSUE TITLE
2.0.4-v.2 - Unexpected white bulges left and right on login page 

### ISSUE THREAD

**Issue by TheDutchJewel** [jon48/webtrees-theme-rural#8]
See the unexpected white bulges left and right on the login page:
![afbeelding](https://user-images.githubusercontent.com/46184729/83976529-bb8b9980-a8fa-11ea-9ca7-cfa810bbe84b.png)

I suppose this is not as intended.

**Comment by jon48** [comment]
No, this is not intended.
However, this is again a case I have not managed to reproduce yet. 

![image](https://user-images.githubusercontent.com/5150782/83980297-5e98df00-a90c-11ea-8d74-b83de2afa477.png)

Do you know how to use the Developer Tools of your browser? I would be interested to see the HTML structure of your footers, and as well the computed value of the `max-field` property for the `footer` element, with the expanded detail of its source. I am adding a screenshot of the Edge tools.

![image](https://user-images.githubusercontent.com/5150782/83980509-73767200-a90e-11ea-9c95-e7ef2e1c1d16.png)

**Comment by TheDutchJewel** [comment]
![afbeelding](https://user-images.githubusercontent.com/46184729/83995337-70ed3a00-a959-11ea-94bc-955430c0373b.png)

**Comment by TheDutchJewel** [comment]
![afbeelding](https://user-images.githubusercontent.com/46184729/83995800-b100ec80-a95a-11ea-8e57-7be11d2e14a4.png)

**Comment by jon48** [comment]
Thanks. Interesting it is putting the priority on the `container` class rather than the `wt-footers` (which would be setting the width correctly), it orders them correctly on my side, and I would expect `container` to be less CSS specific.

I have tried making the `wt-footers` more specific, but I cannot test it myself. Could you please try replacing the file `/modules_v4/myartjaub_ruraltheme/resources/css/rural.min.css` with the file in [this archive](https://github.com/jon48/webtrees-theme-rural/files/4744715/rural.min.css.zip) (this would include the fix for your other issue #9 with sources as well) ?

**Comment by TheDutchJewel** [comment]
Works fine for both issues.
Thanks for fixing!
